{% set name = "OSMPythonTools" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/OSMPythonTools-{{ version }}.tar.gz
  sha256: 13ff721f760fdad5dd78b4d1461d286b78bba96ee151a7301ee8c11a0c258be9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4
    - geojson
    - lxml
    - matplotlib-base
    - numpy
    - pandas
    - ujson
    - xarray

test:
  imports:
    - OSMPythonTools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mocnik-science/osm-python-tools
  summary: A library to access OpenStreetMap related services.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rosepearson
    - mocnik-science
